### ISSUE TITLE
Instructions in README does not install `berks`

### ISSUE THREAD

**Issue by emersonknapp** [ros-infrastructure/ros2-cookbooks#6]
In going through the instructions to get a machine set up - I found I did not have `berks`. Seems like `cinc` doesn't install this utility.

Here's what I did to get it, not sure if this is a good way. If it is, I'm happy to open a PR to add instructions to the README

```
choco install ruby
# open new powershell
ridk install
# default options, click through pop up installer
gem install berkshelf
```

@brawner thoughts?

**Comment by brawner** [comment]
Yes it looks like that part is missing. In the related CI PR (https://github.com/ros2/ci/pull/425) that will be merged soon, I just install chefdk with choco. That would be awesome if you could open another PR for this change.

```
choco install -y git chefdk
```

I appreciate that you're testing out the cookbook. Let me know if you have any more troubles.

**Comment by emersonknapp** [comment]
Ah - using a choco install seems easier than the above. Does `choco install chefdk` get you everything that the `cinc` install does, or do we need both? 

The README is also referring to the `solo.rb` that exists on the `ros2/ci` side, so I am now un-confused on that part. It would make sense to me to just include that default config file here in with the cookbooks - what do you think?

**Comment by nuclearsandwich** [comment]
> Ah - using a choco install seems easier than the above. Does `choco install chefdk` get you everything that the `cinc` install does, or do we need both?

I'm going to put this info in on drive-by in the hope that it is useful. I think the solution I would advocate for is unavailable at the moment and as a result any solution is fine with me.

The `ChefDK` Chef Development Kit is a deprecated distribution of Chef tools for developing chef cookbooks. We need it for `berks` since we aren't currently using a chef-server which would store cookbook dependencies or vendoring our cookbook dependencies directly in this repository, so they need to be resolved before use.

ChefDK has been superceded by Chef Workstation which can be installed via their omnitruck install script https://docs.chef.io/chef_install_script/

Recent versions of chef have license-encumbered binaries which are not free to use for commercial use. To avoid that mess entirely we're trying to use binaries distributed by the Cinc.sh project (roughly the CentOS to Chef's RHEL) but cinc does not yet have workstation binaries for Windows.

I haven't checked on the Cinc project's status for Windows binaries of workstation but I would like the Open Robotics project to switch to that as soon as possible. I also don't know how recent that chefdk binary distribution in chocolatey is or how long it will be updated so perhaps it's worth using the Chef Workstation installer instead?

**Comment by emersonknapp** [comment]
For now at least, this issue is resolved by the updated instructions in https://github.com/ros-infrastructure/ros2-cookbooks/pull/10
